name: shopfusion
description: Basic Shopping Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_insta: ^1.0.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  connectivity: ^3.0.6
  flutter_svg: ^2.0.6
  flutter_fimber: ^0.6.0
  fluttertoast: ^8.2.2
  intl: ^0.18.0
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  flutter_downloader: ^1.10.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/
   
  fonts:
   - family: InstrumentSans-Bold
     fonts:
        - asset: assets/fonts/InstrumentSans-Bold.ttf
   - family: InstrumentSans-Medium
     fonts:
        - asset: assets/fonts/InstrumentSans-Medium.ttf
   - family: InstrumentSans-SemiBold
     fonts:
        - asset: assets/fonts/InstrumentSans-SemiBold.ttf
   - family: InstrumentSans-Regular
     fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf


analyzer:
  stronge-mode: true
  language:
    enableSuperMixins: true